#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Nov 22, 2015 08:31:06 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top38
    namespace eval ::widgets::$base {
        set dflt,origin 1
        set runvisible 1
    }
    set site_3_0 $base.fra48
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top38 {base} {
    if {$base == ""} {
        set base .top38
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m37" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 320x128
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 4264 1672
    wm minsize $top 126 10
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Project"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TLabel -background #d9d9d9
    ttk::style configure TLabel -foreground #000000
    ttk::style configure TLabel -font TkDefaultFont
    ttk::label $top.tLa39 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Connection 
    vTcl:DefineAlias "$top.tLa39" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa40 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Working Directory} 
    vTcl:DefineAlias "$top.tLa40" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn41 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn41" "connection_entry" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn42 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn42" "dir_entry" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu44 \
        -takefocus {} -text ... 
    vTcl:DefineAlias "$top.tBu44" "connection_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu45 \
        -takefocus {} -text ... 
    vTcl:DefineAlias "$top.tBu45" "svn_button" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 175 
    vTcl:DefineAlias "$top.fra48" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.cpd49 \
        -takefocus {} -text OK 
    vTcl:DefineAlias "$site_3_0.cpd49" "ok_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.cpd50 \
        -takefocus {} -text Cancel 
    vTcl:DefineAlias "$site_3_0.cpd50" "cancel_button" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.cpd49 \
        -in $site_3_0 -x 0 -y 0 -anchor nw -bordermode inside 
    place $site_3_0.cpd50 \
        -in $site_3_0 -x 90 -y 0 -width 76 -height 25 -anchor nw \
        -bordermode inside 
    menu $top.m37 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa39 \
        -in $top -x 20 -y 20 -anchor nw -bordermode ignore 
    place $top.tLa40 \
        -in $top -x 20 -y 60 -anchor nw -bordermode ignore 
    place $top.tEn41 \
        -in $top -x 130 -y 20 -width 136 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tEn42 \
        -in $top -x 130 -y 60 -width 136 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tBu44 \
        -in $top -x 270 -y 20 -width 26 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.tBu45 \
        -in $top -x 270 -y 60 -width 26 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.fra48 \
        -in $top -x 130 -y 90 -width 175 -height 35 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top38

